language: java
script: mvn package
deploy:
  provider: script
  script: ./travis/deploy.sh
  on:
    branch: master

env:
  global:
  - OSSRH_JIRA_USERNAME=navikt
  - secure: ITqkbzP1MhQYTUNpvVolIom/LDPx2SXKzEG+Pv04YjBRKr75k+pMvamrmbwRqTXR5VfdofBHbHcLW86gucAh0X17BqH4/FlbeRtXoRdrB5Nw1/gL2ulfpaQcko1RynVH+ZMF8MSNYV4Ta3Sy1ASvYkc0SN/I49dEyvon62apQyDJOPjTjK4wDtjucTlsgf1SbMbuW+KrdmY4yrz9YZm1dJAagRrU4tEAAlTZYwDNLyrXfBrTNJNwQk59eRIZB7eGzvi6c003vE0zyA6DyGt2qL/tgsvaJ2Z3/7V/Nztz7Ow3YVh44T1fWMoDf34gU65eyypHSgqx614UYVq+M1XW58kjdQtGk8PPh0ac4LsNN6sHIqridL5ufwfclWlM/p1ibN69iBgc7ZUALUcovtQrBHlaTjBc0oi1mMggwsw8nqMqjiOflrdeVUEK0XX1DssbNfzkw+WArXkvBMKxif/8iAe2jbn12xIMgB6xTHu9ASkZh4fpzXmDil6i7kAVfE+tj8xOU3ttPog1cwhM0up16T28ipfQHgdjsblxdOlcfdTATcQxIW9KFUplqwOb+012CILGLn8YsAIks135uS5tinGSB+Z1cdKy4RQ+6TzIgqrrnhdM9OqLpSwhjsDr63qHlJOHhPnpZyE4vX5kGEkxyYct2BgUs9LupWGcTqgsRfg=
  - GPG_KEY_NAME=navikt
  - secure: iDZ8ftqEAa5P4PvTejtHI2VPC/uiqV1r1lRCcdCgYV8QZYnw4LsTFG8ZxdWeRngiOKFkKPoSJS9jfwRKQFFqb27OgzstknRraTCgKwrXgQQMfbQfhp8rn7B9UgdDsoxSkjfmPiaW8fJKtMsxmsncNWFzaA6V5JdVbJysqbSEP61JYyKRrDGBUZEoBNr2UhuVV6A4vxxq6ZxEZR22qtdTPk7Dli8HbFiPB1K4z09kRHCBiXlmURQ1mxRuIW6xhe53os2hjnYFpVnCuVXZkO7przGyWYDbk270PRAUUu7dj+kbAjw30IwmpEcSfZdApKQsiJUgluPYLNxKd2w9h2nFi00RvRNs7GE8o6ywF7htrzxNZLuv/HmGw73TNNh/eUIbmXnyYP1qpHL9L+WjP8u4KaJ5qC9ruDYVagwBMIFzvqxPv/yfMbTNPGL+gNnidL7PC0naP1Ozy9f7t2XQc2TN+kqFtZaVs5lxtX/q0vhSZoK+VdtHTPcvxqPCChoIb7wf/fUMhyY5bL+rChQFUKyspuSb2Dd+2L1ofqrsOw0R54xWqzuAFFybXPf3uNeQOs8C60s6b5MP5ogndwq4IsiSgkKBTFxhoM2Es3Holmv0P0cYP4A+nlThrXBR2AN54RNJx31BGCV3EdGtDoR2/bjSvhpmQyA3RexdB8SvjOfAx6w=
